### ISSUE TITLE
Deploy failed: `Error occurred prerendering page "/ui/dashboard/menuLink". Read more: `

### ISSUE THREAD

**Issue by Annedrew** [Annedrew/dashboard#2]
Error information:

```
Error occurred prerendering page "/ui/dashboard/menuLink". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'path')
    at MenuLink (/Users/ningan/Documents/github/dashboard/.next/server/chunks/3895.js:1:280)
    at nk (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38654)
    at nC (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:54802)
    at nw (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38210)
    at nk (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:38805)
    at nk (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:51944)
    at nC (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:54802)
    at nR (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:57452)
    at nE (/Users/ningan/Documents/github/dashboard/node_modules/next/dist/compiled/next-server/app-page.runtime.prod.js:28:56859)
    at nC (/Users/ningan/Documents/github/dashboard
 ✓ Generating static pages (20/20) 

> Export encountered errors on following paths:
        /ui/dashboard/menuLink/page: /ui/dashboard/menuLink
```

**Comment by Annedrew** [comment]
Fix process:
1. Before deploy on vercel, you can first deploy it locally, just by run `npm run build`, if there is no error, you can deploy it on vercel.
2. Locate the error: `TypeError: Cannot read properties of undefined (reading 'path')`
3. Add a check snippet, to make sure, `href` is always avaliable.
```
if (!item) return null;
```
